name: Update README with activity

on:
  schedule:
    - cron: '0 * * * *'   # runs hourly
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
