name: Update Learning Section

on:
  schedule:
    - cron: '0 12 * * 1'   # runs every Monday at noon
  workflow_dispatch:

jobs:
  update-learning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update Learning
        uses: andymatuschak/auto-insert-text@v1
        with:
          file: README.md
          marker: "<!--START_SECTION:learning-->,<!--END_SECTION:learning-->"
          content-file: learning.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "chore: update learning section"
          git push
