name: Update Learning Section

on:
  schedule:
    - cron: '0 12 * * 1'   # every Monday at noon UTC
  workflow_dispatch:

jobs:
  update-learning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Insert learning.md into README.md
        run: |
          # Read learning.md into a variable
          CONTENT="$(cat learning.md)"

          # Escape slashes for sed
          CONTENT_ESCAPED=$(printf '%s\n' "$CONTENT" | sed 's/[&/\]/\\&/g')

          # Replace everything between the markers in README.md
          sed -i "/<!--START_SECTION:learning-->/, /<!--END_SECTION:learning-->/c\\<!--START_SECTION:learning-->\\
$CONTENT_ESCAPED\\
<!--END_SECTION:learning-->" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "chore: update learning section"
          git push
