name: Update Learning Section

on:
  schedule:
    - cron: '0 12 * * 1'   # runs every Monday at noon
  workflow_dispatch:

jobs:
  update-learning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read learning.md
        id: learning
        run: |
          echo "CONTENT<<EOF" >> $GITHUB_ENV
          cat learning.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Replace Learning Section in README
        uses: peter-evans/replace-text@v2
        with:
          files: README.md
          placeholder: '<!--START_SECTION:learning-->[\s\S]*<!--END_SECTION:learning-->'
          replacement: '<!--START_SECTION:learning-->\n${{ env.CONTENT }}\n<!--END_SECTION:learning-->'

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "chore: update learning section"
          git push
