name: Update Learning Section

on:
  schedule:
    - cron: '0 12 * * 1'   # every Monday at noon UTC
  workflow_dispatch:

jobs:
  update-learning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README from learning.md
        run: |
          set -e
          python3 - <<'PY'
          import re, sys, os

          print("DEBUG: Current diretory contents:", os.listdir())
          
          try:
              with open('learning.md', 'r', encoding='utf-8') as f:
                  content = f.read().rstrip()
          except FileNotFoundError:
              print('learning.md not found', file=sys.stderr)
              sys.exit(1)
              
          try:
              with open('README.md', 'r', encoding='utf-8') as f:
                  readme = f.read()
          except FileNotFoundError:
              print('README.md not found; creating one', file=sys.stderr)
              readme = ''

          print("DEBUG: Successfully read both files")
          
          start = '<!--START_SECTION:learning-->'
          end = '<!--END_SECTION:learning-->'
          replacement = f"{start}\n{content}\n{end}"
          pattern = re.compile(re.escape(start) + r'.*?' + re.escape(end), re.DOTALL)
          if pattern.search(readme):
              new_readme = pattern.sub(replacement, readme)
          else:
              # If markers aren't present, append section at the end
              if readme and not readme.endswith('\n'):
                  readme += '\n'
              new_readme = readme + '\n' + replacement
          if new_readme != readme:
              with open('README.md', 'w', encoding='utf-8') as f:
                  f.write(new_readme)
              print('README.md updated')
          else:
              print('No changes needed')
          PY

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update learning section"
            git push
          fi
