name: Update Learning Section

on:
  schedule:
    - cron: '0 12 * * 1' # every Monday at noon UTC
  workflow_dispatch:

jobs:
  update-learning:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Python to update README
        run: python3 update_learning.py

name: Commit changes
  run: |
    git config --global user.name 'github-actions'
    git config --global user.email 'actions@github.com'
    git add README.md
    # Only commit if there are changes
    if git diff --cached --quiet; then
      echo "No changes to commit"
    else
      git commit -m "chore: update learning section"
      git push origin HEAD
    fi

